### ISSUE TITLE
Add AD to the App Settings Configuration

### ISSUE THREAD

**Issue by robinmanuelthiel** [MikeCodesDotNet/Mobile-Cloud-Workshop#21]
So that participants can update ADB2C settings without changing code

**Comment by MikeCodesDotNet** [comment]
Looks like this could call under a winder scope of work to do with app settings: 

https://github.com/MikeCodesDotNet/Mobile-Cloud-Workshop/issues/26

**Comment by robinmanuelthiel** [comment]
Oh, I was not talking about the Web App's appsettings.json but the Settings PAGE in the app. The idea is still to let users download the app without the need to change Frontend code.
