### ISSUE TITLE
Add Azure Active Directory to Architecture Diagram

### ISSUE THREAD

**Issue by robinmanuelthiel** [MikeCodesDotNet/Mobile-Cloud-Workshop#25]

**Comment by MikeCodesDotNet** [comment]
![arch-auth](https://user-images.githubusercontent.com/552074/37862477-a8224eda-2f4d-11e8-9512-1ce59370fc65.png)
If you're happy with the above then I think we can update the docs and close this issue.

**Comment by robinmanuelthiel** [comment]
At this step, we should also replace "Mobile Center" with "App Center" and replace Region with "Mobile DevOps" or something

**Comment by MikeCodesDotNet** [comment]
![arch-ad draft2](https://user-images.githubusercontent.com/552074/37873826-512ce66c-3024-11e8-8163-0c2277412bed.png)

@robinmanuelthiel ^^

**Comment by robinmanuelthiel** [comment]
Awesome!
