### ISSUE TITLE
Search settings using incorrect name (causes search to not work)

### ISSUE THREAD

**Issue by MikeCodesDotNET** [MikeCodesDotNET/Mobile-Cloud-Workshop#26]
Commit cb6dab2a249ac0b6ca411e0109d86ead1af485ba breaks search. 

It looks like @robinmanuelthiel moved everything to appsettings.json for tidier code but got a name wrong causing search to simply not work. 

I've fixed this in a branch thats implementing some extra search functionality so we'll get this fixed in our public branch soon. 

### Current Settings
    "AzureSearch": {
        "AzureSearchServiceName": "contosomaintenance",
        "AzureSearch:AzureSearchApiKey": "5F01767846A092CB8678973CA05D5B60"
    },

### The Fix
    "AzureSearch": {
        "AzureSearchServiceName": "contosomaintenance",
        "AzureSearchApiKey": "5F01767846A092CB8678973CA05D5B60"
    },

## Next steps
before we close this issue, it'll be good to do a sanity check of all settings used through the project to confirm we've not got any other issues that are similar.

**Comment by robinmanuelthiel** [comment]
Rest should work. Skipped Azure Search in my sessions so far so I didn't notice.

**Comment by jameslavery** [comment]
I think the current master still has the incorrect AzureSearch settings in appsettings.json.

I had to edit to the following to get it to work (was getting a null apiKey error when testing Search via the API  Management service):

```
    "AzureSearch": {
        "AzureSearchServiceName": "mysearchname",
        "AzureSearchApiKey": "mysearchkey",
    },
```

**Comment by jameslavery** [comment]
I've correct this locally - can submit once I've got PR sorted out.
