### ISSUE TITLE
Search Suggestions Hit-Highlighting can cause some oddness in title names

### ISSUE THREAD

**Issue by MikeCodesDotNET** [MikeCodesDotNET/Mobile-Cloud-Workshop#27]

**Comment by MikeCodesDotNet** [comment]
![simulator screen shot - iphone x - 2018-03-25 at 11 57 54](https://user-images.githubusercontent.com/552074/37873794-c57cd0aa-3023-11e8-9e53-f9e8614e6178.png)

![simulator screen shot - iphone x - 2018-03-25 at 11 57 58](https://user-images.githubusercontent.com/552074/37873795-c79cc4c6-3023-11e8-9c87-a0e9c32aebfb.png)

If hit-hightlight spans multiple words then we don't create the correct spans.

**Comment by MikeCodesDotNET** [comment]
I've resolved this by rewriting our hit-highlight logic within the Extensions class. 

We now no longer use Regex which has simplified things a little as we're either going to split the string in 2 or 3 parts for the highlighting.

**Comment by robinmanuelthiel** [comment]
Nice!
