### ISSUE TITLE
Job Details Keys are misaligned

### ISSUE THREAD

**Issue by robinmanuelthiel** [MikeCodesDotNET/Mobile-Cloud-Workshop#41]
![screenshot_20180412-232453](https://user-images.githubusercontent.com/5874465/38705662-984832a6-3eaa-11e8-9a65-68c44e0acff1.jpg)

**Comment by MikeCodesDotNet** [comment]
Sorry? What am I looking at here?

**Comment by robinmanuelthiel** [comment]
Why did you close?

**Comment by MikeCodesDotNET** [comment]
Not enough info to see what the issue is. Went a closed a few that didn't have information.
