### ISSUE TITLE
Search Crashes App

### ISSUE THREAD

**Issue by MikeCodesDotNET** [MikeCodesDotNET/Mobile-Cloud-Workshop#44]
https://github.com/MikeCodesDotNet/Mobile-Cloud-Workshop/blob/af4227bdab9f46264f5756da14593e51cb1423e9/Mobile/ContosoFieldService.Core/ViewModels/Jobs/JobsViewModel.cs#L101

The app crashes here when searching. I really really HATE how Grouping is implemented in Forms and would love to just remove this entirely (not a fault of RM, he implemented according to the savages that created the library). 

Right now I'm unsure if this a grouping bug, an MvvmHelper bug (with Motz's RangeCollection) or something else. 

Lets chat on Monday about how to fix this part of the app as its incredibly important.

**Comment by jameslavery** [comment]
Is this still happening? I'm able to search from the app fine.

**Comment by MikeCodesDotNET** [comment]
Just discovered why I'm seeing this issue, its only in our production instance as our current deployment is misconfigured. Search works as expected if deployed on its own if we ignore the issue with #65.
