### ISSUE TITLE
Simplify walkthrough instructions for multiple areas. 

### ISSUE THREAD

**Issue by robinmanuelthiel** [MikeCodesDotNET/Mobile-Cloud-Workshop#54]
## Improvement ideas
- Remove need to specify `DatabaseId` for AppService
- Remove need to specify `PhotosBlobContainerName` and `QueueName` for AppService and let logic create containers and queue when not existent
- Use Cosmos DB Connection String instead of URI and Key in AppService (like it is in the Function)
- Rename `Ocp-Apim-Subscription-Key` in Azure Function to something more descriptive

**Comment by MikeCodesDotNET** [comment]
I think theres a fair bit of value from having delegates creation the photoprocess queue and the blob containers. I think we could possibly have them create just 1 container for the large images and automagically create the medium and icon container later.
