### ISSUE TITLE
Azure Functions only support one way of Monitoring now: Application Insights

### ISSUE THREAD

**Issue by robinmanuelthiel** [MikeCodesDotNET/Mobile-Cloud-Workshop#57]

**Comment by robinmanuelthiel** [comment]
Still missing this in our docs!

**Comment by MikeCodesDotNET** [comment]
Closed this as there was no info. Now I know you're talking about docs I have a bit better understanding of why this was created.

**Comment by robinmanuelthiel** [comment]
We need to update the docs so that Azure Functions Monitoring is switched to App Insights. I will do that
