### ISSUE TITLE
Login page does not display properly on smaller Android devices

### ISSUE THREAD

**Issue by jameslavery** [MikeCodesDotNET/Mobile-Cloud-Workshop#64]
When running against an Android emulator with a smaller screen size, the _Login_ button covers the main screen text.
![screenshot_1528896823](https://user-images.githubusercontent.com/39184499/41354574-3f13f2e0-6f17-11e8-83b4-656eb907b268.png)

This is not optimal when demonstrating! A workaround of course is to demonstrate on larger devices.

**Comment by MikeCodesDotNET** [comment]
@robinmanuelthiel is our Android man. Maybe he can make it beautiful.
